version: '3.8'


services:
  server-dev-hotreload:
    container_name: webserver
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    volumes:
      - ./social-network-server:/app
      - /tmp/images:/images
  server-dev:
    container_name: webserver
    build: social-network-server
    image: social-network-server:v5
    volumes:
      - /tmp/images:/images
  mysql:
    container_name: mysqldb
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./social-network-server/db_migration/:/docker-entrypoint-initdb.d
  mysql-dev:
    container_name: mysqldb
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    volumes:
      - ./social-network-server/db_migration/:/docker-entrypoint-initdb.d
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 5556:80
    volumes:
      - ./social-network/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/images:/data/images
  nginx-with-front:
    container_name: front_nginx
    build: social-network
    image: social-network-frontend:v1
    ports:
      - 5556:80
    volumes:
      - /tmp/images:/data/images