---
pvc:
    name: standard-pvc
    storage_class_name: "standard" # Use class storage that allows share data between nodes. In case minikube use 'standard' or leave blank for default value
    storage: 1Gi

frontend:
    app_name: "social-network-frontend"
    image: "prafdin/social-network:v1.6"
    port: 80
    requests:
        memory: 128Mi
        cpu: 100m
    limits:
        memory: 128Mi
        cpu: 100m

backend:
    app_name: "social-network-backend"
    port: 8080
    image: "prafdin/social-network-server:v1.3"
    requests:
        memory: 128Mi
        cpu: 100m
    limits:
        memory: 256Mi
        cpu: 200m
    db:
        name: social_network_db
        user: root
        password: admin
        url: mysql-svc.mysql


