---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.backend.app_name }}-configmap'
data:
  config.yaml: |
    DB_USER={{ .Values.backend.db.user }}
    DB_PASS={{ .Values.backend.db.password }}
    DB_URL={{ .Values.backend.db.url }}
    DB_NAME={{ .Values.backend.db.name }}
