---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.pvc.name }}"
spec:
  storageClassName: "{{ .Values.pvc.storage_class_name }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.pvc.storage }}"
