---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.backend.app_name }}-svc'
spec:
  ports:
    - port: '{{ .Values.backend.port }}'
  selector:
    app: '{{ .Values.backend.app_name }}'
  clusterIP: None
