---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.frontend.app_name }}-svc'
spec:
  ports:
    - port: {{ .Values.frontend.port }}
  selector:
    app: {{ .Values.frontend.app_name }}
  clusterIP: None
