---
apiVersion: v1
kind: Service
metadata:
  name: social-network-server-svc
spec:
  ports:
    - port: 8080
  selector:
    app: social-network-server
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: social-network-server
data:
  config.yaml: |
    DB_USER=root
    DB_PASS=admin
    DB_URL=wp-mysql-svc.mysql
    DB_NAME=social_network_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-network-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-network-server
  template:
    metadata:
      labels:
        app: social-network-server
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: social-network-server
          image: prafdin/social-network-server:v1.3
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: images-vol
              mountPath: /images
            - name: config
              mountPath: /var/app.properties
              subPath: config.yaml
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
      volumes:
        - name: images-vol
          persistentVolumeClaim:
            claimName: standart-pvc
        - name: config
          configMap:
            name: server-config
